name: Frontend CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-tests.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-tests.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18, 20]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock
          
      - name: Install dependencies
        working-directory: frontend
        run: yarn install --frozen-lockfile
        
      - name: TypeScript check
        working-directory: frontend
        run: yarn typecheck || npx tsc --noEmit
        
      - name: Lint check
        working-directory: frontend
        run: yarn lint
        
      - name: Run tests with coverage
        working-directory: frontend
        run: yarn test:ci
        env:
          NODE_ENV: test
          
      - name: Check coverage threshold
        working-directory: frontend
        run: |
          yarn test:coverage --passWithNoTests --coverageThreshold='{"global":{"branches":80,"functions":80,"lines":80,"statements":80}}'
        
      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage-${{ matrix.node-version }}
          path: frontend/coverage
          retention-days: 30
          
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          directory: frontend/coverage
          flags: frontend
          name: frontend-coverage
          fail_ci_if_error: false

  expo-doctor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock
          
      - name: Install dependencies
        working-directory: frontend
        run: yarn install --frozen-lockfile
        
      - name: Install Expo CLI
        run: npm install -g @expo/cli
        
      - name: Run Expo Doctor
        working-directory: frontend
        run: npx expo doctor